//! Typed identifiers.
//!
//! Entity ids are 128-bit ULIDs: time-sortable, generated by whichever
//! component creates the entity, and never reused. Content ids are BLAKE3
//! digests of the content they name, so the same content always has the same
//! id on every node.
//!
//! No id type converts into another, and none is a bare integer or string at
//! a module boundary.

use crate::support::Blake3;

macro_rules! entity_id {
    ($($(#[$doc:meta])* $name:ident;)*) => {$(
        $(#[$doc])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(u128);

        impl $name {
            pub const fn from_ulid(raw: u128) -> Self {
                Self(raw)
            }

            pub const fn as_ulid(self) -> u128 {
                self.0
            }
        }
    )*};
}

macro_rules! content_id {
    ($($(#[$doc:meta])* $name:ident;)*) => {$(
        $(#[$doc])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(Blake3);

        impl $name {
            pub const fn from_digest(digest: Blake3) -> Self {
                Self(digest)
            }

            pub const fn digest(&self) -> &Blake3 {
                &self.0
            }
        }
    )*};
}

entity_id! {
    /// An agent: whoever is behind a stream of exchanges.
    AgentId;
    /// A threaded conversation reconstructed from exchanges.
    ConversationId;
    /// One request/response round trip through the proxy.
    ExchangeId;
    /// A located run of text inside one message.
    SpanId;
    /// One concrete locator an agent touched (a URL, a file path).
    ResourceId;
    /// One read or write of a resource by an agent.
    AccessId;
    /// A group of resources that act as one communication medium.
    ChannelId;
    /// One agent-to-agent communication.
    TransmissionId;
    /// A topic produced by the topic model.
    TopicId;
    /// A configured alert rule.
    AlertRuleId;
    /// One raised alert.
    AlertId;
    /// A human who reviews policy and triages alerts.
    OperatorId;
    /// One event on the bus. Consumers deduplicate on it.
    EventId;
}

content_id! {
    /// The canonical encoding of one message. Two identical messages in two
    /// requests have the same hash, which is how request histories dedupe.
    MessageHash;
    /// An API key, hashed at the proxy. The raw key is never stored.
    KeyHash;
    /// A system prompt plus the first user turn: a weak identity signal for
    /// agents that share a key.
    PromptHash;
}
