//! Typed identifiers.
//!
//! Entity ids are 128-bit ULIDs: time-sortable, generated by whichever
//! component creates the entity, and never reused. Content ids are BLAKE3
//! digests of the content they name, so the same content always has the same
//! id on every node. Secret digests are keyed BLAKE3 of values that must not
//! be recoverable or confirmable (credentials, account ids).
//!
//! No id type converts into another, and none is a bare integer or string at
//! a module boundary.
//!
//! On the wire ([`crate::wire`]) an entity id is its ULID text
//! ([`AgentId::ulid_text`]), a content id its digest's lower-case hex, and a
//! secret digest `{"key": <secret version>, "digest": "<hex>"}`. Decoding
//! accepts only those canonical forms. Entity ids are [`WireRequest`]s: a
//! client names entities by id.

use serde::{Deserialize, Deserializer, Serialize, Serializer};

use crate::support::Blake3;
use crate::wire::{WireRequest, decode_text};

macro_rules! entity_id {
    ($($(#[$doc:meta])* $name:ident;)*) => {$(
        $(#[$doc])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(u128);

        impl $name {
            pub const fn from_ulid(raw: u128) -> Self {
                Self(raw)
            }

            pub const fn as_ulid(self) -> u128 {
                self.0
            }

            /// The id as ULID text: 26 upper-case characters of Crockford
            /// base32, most significant first. The form ids take in URLs and
            /// JSON, and the form an agent filter's text is matched against.
            pub fn ulid_text(self) -> String {
                ulid_text(self.0)
            }

            /// The id `text` names, accepting exactly the text
            /// [`Self::ulid_text`] writes.
            pub fn from_ulid_text(text: &str) -> Result<Self, InvalidUlidText> {
                parse_ulid_text(text).map(Self)
            }
        }

        impl Serialize for $name {
            fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                serializer.serialize_str(&self.ulid_text())
            }
        }

        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                decode_text(deserializer, "ULID text", |text| Self::from_ulid_text(&text))
            }
        }

        impl WireRequest for $name {}
    )*};
}

/// Crockford's base32 alphabet: digits and upper-case letters without I, L,
/// O and U.
const CROCKFORD: &[u8; 32] = b"0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/// 128 bits as 26 base32 digits: the first carries the top 3 bits, each
/// later one 5.
fn ulid_text(raw: u128) -> String {
    (0..26u32)
        .rev()
        .map(|digit| {
            let index = (raw >> (5 * digit)) & 0x1f;
            char::from(CROCKFORD[index as usize])
        })
        .collect()
}

/// Why text is not an entity id.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InvalidUlidText {
    /// Not 26 bytes.
    Length { got: usize },
    /// The byte at `index` is not in Crockford's upper-case alphabet. Lower
    /// case and the excluded letters (I, L, O, U) are refused, so every id
    /// has one text.
    Character { index: usize },
    /// The first digit is above 7: the value needs more than 128 bits.
    Overflow,
}

/// The inverse of [`ulid_text`].
fn parse_ulid_text(text: &str) -> Result<u128, InvalidUlidText> {
    let bytes = text.as_bytes();
    if bytes.len() != 26 {
        return Err(InvalidUlidText::Length { got: bytes.len() });
    }
    let mut raw: u128 = 0;
    for (index, byte) in bytes.iter().enumerate() {
        let digit = CROCKFORD
            .iter()
            .position(|symbol| symbol == byte)
            .ok_or(InvalidUlidText::Character { index })?;
        if index == 0 && digit > 7 {
            return Err(InvalidUlidText::Overflow);
        }
        raw = (raw << 5) | digit as u128;
    }
    Ok(raw)
}

macro_rules! content_id {
    ($($(#[$doc:meta])* $name:ident;)*) => {$(
        $(#[$doc])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(Blake3);

        impl $name {
            pub const fn from_digest(digest: Blake3) -> Self {
                Self(digest)
            }

            pub const fn digest(&self) -> &Blake3 {
                &self.0
            }
        }

        impl Serialize for $name {
            fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                self.0.serialize(serializer)
            }
        }

        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                Blake3::deserialize(deserializer).map(Self)
            }
        }
    )*};
}

entity_id! {
    /// An agent: whoever is behind a stream of exchanges.
    AgentId;
    /// One recorded merge, so it can be reverted exactly.
    MergeId;
    /// A stored projection (layout of transmission embeddings).
    ProjectionId;
    /// A configured alert sink.
    SinkId;
    /// A threaded conversation reconstructed from exchanges.
    ConversationId;
    /// One request/response round trip through the proxy.
    ExchangeId;
    /// A located run of text inside one message.
    SpanId;
    /// One concrete locator an agent touched (a URL, a file path).
    ResourceId;
    /// One read or write of a resource by an agent.
    AccessId;
    /// A group of resources that act as one communication medium.
    ChannelId;
    /// One agent-to-agent communication.
    TransmissionId;
    /// A topic produced by the topic model.
    TopicId;
    /// A configured alert rule.
    AlertRuleId;
    /// One raised alert.
    AlertId;
    /// A human who reviews policy and triages alerts.
    OperatorId;
    /// One event on the bus. Consumers deduplicate on it.
    EventId;
    /// One audit log entry: an operator action call or a change config made.
    AuditId;
    /// One export: its header, its trailer and its audit entries name it.
    ExportId;
}

content_id! {
    /// The canonical encoding of one message. Two identical messages in two
    /// requests have the same hash, which is how request histories dedupe.
    MessageHash;
    /// A system prompt plus the first user turn: a weak identity signal for
    /// agents that share a credential.
    PromptHash;
    /// The canonical encoding of one loaded config document. Audit entries
    /// for changes config made name the document that made them.
    ConfigHash;
}

macro_rules! secret_digest {
    ($($(#[$doc:meta])* $name:ident;)*) => {$(
        $(#[$doc])*
        ///
        /// A BLAKE3 keyed with the deployment's secret, so a stored digest
        /// cannot be used to confirm a guessed value. It records which version
        /// of the secret computed it.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
        #[serde(rename_all = "snake_case", deny_unknown_fields)]
        pub struct $name {
            key: SecretVersion,
            digest: Blake3,
        }

        impl $name {
            pub const fn from_keyed_digest(key: SecretVersion, digest: Blake3) -> Self {
                Self { key, digest }
            }

            pub const fn key(&self) -> SecretVersion {
                self.key
            }

            pub const fn digest(&self) -> &Blake3 {
                &self.digest
            }
        }
    )*};
}

/// A version of the deployment secret that keys [`CredentialHash`] and
/// [`AccountHash`]. Every node loads the same versions. On rotation the new
/// version becomes current while the previous one stays loaded for an overlap
/// period, during which the proxy computes both digests so identity resolution
/// can link evidence across the change. The secret itself is never logged.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SecretVersion(pub u16);

secret_digest! {
    /// A credential (API key, OAuth access token, exchanged token, server
    /// key), hashed at the proxy. The raw credential is never stored.
    CredentialHash;
    /// An account id the harness sends alongside its credential
    /// (ChatGPT-Account-ID).
    AccountHash;
}
