//! Typed identifiers.
//!
//! Entity ids are 128-bit ULIDs: time-sortable, generated by whichever
//! component creates the entity, and never reused. Content ids are BLAKE3
//! digests of the content they name, so the same content always has the same
//! id on every node. Secret digests are keyed BLAKE3 of values that must not
//! be recoverable or confirmable (credentials, account ids).
//!
//! No id type converts into another, and none is a bare integer or string at
//! a module boundary.

use crate::support::Blake3;

macro_rules! entity_id {
    ($($(#[$doc:meta])* $name:ident;)*) => {$(
        $(#[$doc])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(u128);

        impl $name {
            pub const fn from_ulid(raw: u128) -> Self {
                Self(raw)
            }

            pub const fn as_ulid(self) -> u128 {
                self.0
            }
        }
    )*};
}

macro_rules! content_id {
    ($($(#[$doc:meta])* $name:ident;)*) => {$(
        $(#[$doc])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(Blake3);

        impl $name {
            pub const fn from_digest(digest: Blake3) -> Self {
                Self(digest)
            }

            pub const fn digest(&self) -> &Blake3 {
                &self.0
            }
        }
    )*};
}

entity_id! {
    /// An agent: whoever is behind a stream of exchanges.
    AgentId;
    /// One recorded merge, so it can be reverted exactly.
    MergeId;
    /// A stored projection (layout of transmission embeddings).
    ProjectionId;
    /// A configured alert sink.
    SinkId;
    /// A threaded conversation reconstructed from exchanges.
    ConversationId;
    /// One request/response round trip through the proxy.
    ExchangeId;
    /// A located run of text inside one message.
    SpanId;
    /// One concrete locator an agent touched (a URL, a file path).
    ResourceId;
    /// One read or write of a resource by an agent.
    AccessId;
    /// A group of resources that act as one communication medium.
    ChannelId;
    /// One agent-to-agent communication.
    TransmissionId;
    /// A topic produced by the topic model.
    TopicId;
    /// A configured alert rule.
    AlertRuleId;
    /// One raised alert.
    AlertId;
    /// A human who reviews policy and triages alerts.
    OperatorId;
    /// One event on the bus. Consumers deduplicate on it.
    EventId;
    /// One audit log entry: an operator action call or a change config made.
    AuditId;
}

content_id! {
    /// The canonical encoding of one message. Two identical messages in two
    /// requests have the same hash, which is how request histories dedupe.
    MessageHash;
    /// A system prompt plus the first user turn: a weak identity signal for
    /// agents that share a credential.
    PromptHash;
    /// The canonical encoding of one loaded config document. Audit entries
    /// for changes config made name the document that made them.
    ConfigHash;
}

macro_rules! secret_digest {
    ($($(#[$doc:meta])* $name:ident;)*) => {$(
        $(#[$doc])*
        ///
        /// A BLAKE3 keyed with the deployment's secret, so a stored digest
        /// cannot be used to confirm a guessed value. It records which version
        /// of the secret computed it.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name {
            key: SecretVersion,
            digest: Blake3,
        }

        impl $name {
            pub const fn from_keyed_digest(key: SecretVersion, digest: Blake3) -> Self {
                Self { key, digest }
            }

            pub const fn key(&self) -> SecretVersion {
                self.key
            }

            pub const fn digest(&self) -> &Blake3 {
                &self.digest
            }
        }
    )*};
}

/// A version of the deployment secret that keys [`CredentialHash`] and
/// [`AccountHash`]. Every node loads the same versions. On rotation the new
/// version becomes current while the previous one stays loaded for an overlap
/// period, during which the proxy computes both digests so identity resolution
/// can link evidence across the change. The secret itself is never logged.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct SecretVersion(pub u16);

secret_digest! {
    /// A credential (API key, OAuth access token, exchanged token, server
    /// key), hashed at the proxy. The raw credential is never stored.
    CredentialHash;
    /// An account id the harness sends alongside its credential
    /// (ChatGPT-Account-ID).
    AccountHash;
}
