//! `QueryApi::conversation_turns`: one window of turns with their
//! structure and marks, and no text.

use crosstalk_spec::ids::{ConversationId, MessageHash};
use crosstalk_spec::interfaces::l4_provenance::reads::ScanStatus;
use crosstalk_spec::interfaces::l8_surface::conversation::TurnWindow;
use crosstalk_spec::interfaces::l8_surface::conversation::turn::{
    IncrementHistory, MessageParts, MessagePlacement, PartKind, PartMarks, PartShape, Turn,
    TurnContinuation, TurnMessage, TurnOutcome, TurnPage,
};
use crosstalk_spec::observed::conversation::ConversationOrigin;
use crosstalk_spec::observed::exchange::Continuation;
use crosstalk_spec::observed::message::{
    AssistantPart, Message, MessageBody, PartRef, Reasoning, Role, SystemPart, UserPart,
};

use super::Cv;
use super::{index, marks};
use crate::backend::Result;
use crate::backend::fixture::clock::{MINUTE, NOW, plus};
use crate::backend::fixture::world::conversations::{ConversationRecord, Ending, TurnRecord};

/// A message's body: generated by the conversations, or stored by the
/// traffic; `None` once retention dropped it.
pub fn body(ctx: &Cv, hash: MessageHash) -> Option<Message> {
    ctx.conversations
        .body(hash)
        .cloned()
        .or_else(|| ctx.world.blobs.body(hash))
}

/// The kind of each part of `message`, in part order.
pub fn part_kinds(message: &Message) -> Vec<PartKind> {
    match &message.body {
        MessageBody::System(parts) => parts
            .iter()
            .map(|p| match p {
                SystemPart::Text(_) => PartKind::Text,
                SystemPart::Unknown(u) => PartKind::Unknown {
                    kind: u.kind.clone(),
                },
            })
            .collect(),
        MessageBody::User(parts) => parts
            .iter()
            .map(|p| match p {
                UserPart::Text(_) => PartKind::Text,
                UserPart::Media(m) => PartKind::Media(m.kind),
                UserPart::Unknown(u) => PartKind::Unknown {
                    kind: u.kind.clone(),
                },
            })
            .collect(),
        MessageBody::Assistant(parts) => parts
            .iter()
            .map(|p| match p {
                AssistantPart::Text(_) => PartKind::Text,
                AssistantPart::Reasoning(r) => PartKind::Reasoning {
                    visible: matches!(r, Reasoning::Visible { .. }),
                },
                AssistantPart::ToolCall(call) => PartKind::ToolCall {
                    call: call.id.clone(),
                    name: call.name.clone(),
                    execution: call.execution,
                },
                AssistantPart::ServerToolResult(result) => PartKind::ToolResult {
                    call: result.call_id.clone(),
                    outcome: result.outcome,
                },
                AssistantPart::Unknown(u) => PartKind::Unknown {
                    kind: u.kind.clone(),
                },
            })
            .collect(),
        MessageBody::Tool(results) => results
            .iter()
            .map(|r| PartKind::ToolResult {
                call: r.call_id.clone(),
                outcome: r.outcome,
            })
            .collect(),
    }
}

/// The marks on one part of `turn`'s message `hash`. Empty while the scan
/// is pending: the fixture commits a turn's marks all at once.
fn part_marks(
    ctx: &Cv,
    turn: &TurnRecord,
    hash: MessageHash,
    index: u16,
    output: bool,
    pending: bool,
) -> (
    Vec<crosstalk_spec::interfaces::l8_surface::conversation::turn::Inbound>,
    Vec<crosstalk_spec::interfaces::l8_surface::conversation::turn::OutputSpan>,
) {
    if pending {
        return (Vec::new(), Vec::new());
    }
    let part = PartRef {
        message: hash,
        index,
    };
    let inbound = marks::inbound(ctx, turn.exchange, part);
    let spans = if output {
        marks::output_spans(ctx, turn.exchange, part)
    } else {
        Vec::new()
    };
    (inbound, spans)
}

/// The part indexes of `turn`'s message `hash` that hold a mark.
fn marked_parts(ctx: &Cv, turn: &TurnRecord, hash: MessageHash) -> Vec<u16> {
    let conversations = &ctx.conversations;
    let mut parts: Vec<u16> = conversations
        .reads_in(turn.exchange)
        .iter()
        .filter_map(|at| marks::content(ctx, *at))
        .map(|(_, content)| content.read_at().part)
        .chain(
            conversations
                .spans_of(turn.exchange)
                .map(|(_, record)| record.location.part),
        )
        .chain(
            conversations
                .relayed_in(turn.exchange)
                .iter()
                .map(|r| r.location.part),
        )
        .filter(|part| part.message == hash)
        .map(|part| part.index)
        .collect();
    parts.sort_unstable();
    parts.dedup();
    parts
}

fn message(
    ctx: &Cv,
    turn: &TurnRecord,
    hash: MessageHash,
    role: Role,
    placement: MessagePlacement,
    pending: bool,
) -> TurnMessage {
    let output = placement == MessagePlacement::Output;
    let parts = match body(ctx, hash) {
        Some(body) => MessageParts::Shown(
            part_kinds(&body)
                .into_iter()
                .enumerate()
                .map(|(i, kind)| {
                    let at = u16::try_from(i).unwrap_or(u16::MAX);
                    let (inbound, spans) = part_marks(ctx, turn, hash, at, output, pending);
                    PartShape {
                        index: at,
                        kind,
                        text_bytes: body
                            .part_text(at)
                            .ok()
                            .and_then(|t| u32::try_from(t.len()).ok()),
                        inbound,
                        spans,
                    }
                })
                .collect(),
        ),
        None => MessageParts::BodyDropped(
            marked_parts(ctx, turn, hash)
                .into_iter()
                .map(|at| {
                    let (inbound, spans) = part_marks(ctx, turn, hash, at, output, pending);
                    PartMarks {
                        index: at,
                        inbound,
                        spans,
                    }
                })
                .collect(),
        ),
    };
    TurnMessage {
        hash,
        role,
        placement,
        parts,
    }
}

fn turn(ctx: &Cv, record: &ConversationRecord, at: usize) -> Option<Turn> {
    let source = record.turns.get(at)?;
    let pending = ctx.conversations.is_pending(source.exchange);
    let continuation = match &source.continuation {
        Continuation::FullHistory => TurnContinuation::FullHistory,
        Continuation::Increment { connection, .. } => TurnContinuation::Increment {
            connection: *connection,
            history: if at == 0 && record.origin == ConversationOrigin::Root {
                IncrementHistory::Unseen
            } else {
                IncrementHistory::Resolved
            },
        },
    };
    let outcome = match &source.ending {
        Ending::Completed {
            finished_at,
            stop,
            usage,
        } => TurnOutcome::Completed {
            finished_at: *finished_at,
            stop: *stop,
            usage: *usage,
        },
        Ending::Failed { failed_at, failure } => TurnOutcome::Failed {
            failed_at: *failed_at,
            failure: *failure,
        },
    };
    let provenance = if pending {
        ScanStatus::Pending
    } else {
        ScanStatus::Indexed {
            at: plus(source.started_at, MINUTE).min(NOW),
        }
    };
    Some(Turn {
        index: index(at),
        exchange: source.exchange,
        agent: ctx.agent(source.agent),
        started_at: source.started_at,
        protocol: source.protocol,
        transport: source.transport,
        model: source.model.clone(),
        harness: source.harness.clone(),
        ingress: record.ingress.clone(),
        continuation,
        outcome,
        inputs: source
            .inputs
            .iter()
            .map(|entry| {
                let placement = if entry.carried_over {
                    MessagePlacement::CarriedOver
                } else {
                    MessagePlacement::New
                };
                message(ctx, source, entry.message, entry.role, placement, pending)
            })
            .collect(),
        output: source.output.map(|hash| {
            message(
                ctx,
                source,
                hash,
                Role::Assistant,
                MessagePlacement::Output,
                pending,
            )
        }),
        provenance,
    })
}

/// `QueryApi::conversation_turns`.
pub fn window(ctx: &Cv, id: ConversationId, window: &TurnWindow) -> Result<Option<TurnPage>> {
    let Some(record) = ctx.conversations.get(id) else {
        return Ok(None);
    };
    let total = u32::try_from(record.turns.len()).unwrap_or(u32::MAX);
    let turns = window
        .range(total)
        .filter_map(|at| turn(ctx, record, at as usize))
        .collect();
    Ok(Some(TurnPage {
        conversation: id,
        total,
        turns,
    }))
}
